/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swingcalculator;

import javax.swing.ImageIcon;

/**
 *
 * @author Encryptor
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    private static double fnumber;
    private static double snumber;
    private static String operation;
    public Calculator() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Calculator");
        ImageIcon img = new ImageIcon("./icon.png");
        setIconImage(img.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        input = new javax.swing.JLabel();
        prom = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        sin = new javax.swing.JLabel();
        cos = new javax.swing.JLabel();
        tan = new javax.swing.JLabel();
        seven = new javax.swing.JLabel();
        eight = new javax.swing.JLabel();
        nine = new javax.swing.JLabel();
        four = new javax.swing.JLabel();
        five = new javax.swing.JLabel();
        six = new javax.swing.JLabel();
        one = new javax.swing.JLabel();
        two = new javax.swing.JLabel();
        three = new javax.swing.JLabel();
        zero = new javax.swing.JLabel();
        point = new javax.swing.JLabel();
        doublezero = new javax.swing.JLabel();
        binary = new javax.swing.JLabel();
        hexa = new javax.swing.JLabel();
        octal = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        equals = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        clear = new javax.swing.JLabel();
        divison = new javax.swing.JLabel();
        mult = new javax.swing.JLabel();
        subs = new javax.swing.JLabel();
        add = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        input.setFont(new java.awt.Font("Tekton Pro Ext", 0, 16)); // NOI18N
        input.setForeground(new java.awt.Color(255, 255, 255));
        input.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        prom.setBackground(new java.awt.Color(255, 255, 255));
        prom.setFont(new java.awt.Font("Tekton Pro Ext", 0, 12)); // NOI18N
        prom.setForeground(new java.awt.Color(255, 255, 255));
        prom.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(input, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(prom, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(prom, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBackground(new java.awt.Color(28, 42, 57));

        sin.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        sin.setForeground(new java.awt.Color(255, 255, 255));
        sin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sin.setText("sin");
        sin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sinMouseClicked(evt);
            }
        });

        cos.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        cos.setForeground(new java.awt.Color(255, 255, 255));
        cos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cos.setText("cos");
        cos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cosMouseClicked(evt);
            }
        });

        tan.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        tan.setForeground(new java.awt.Color(255, 255, 255));
        tan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tan.setText("tan");
        tan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tanMouseClicked(evt);
            }
        });

        seven.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        seven.setForeground(new java.awt.Color(255, 255, 255));
        seven.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        seven.setText("7");
        seven.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sevenMouseClicked(evt);
            }
        });

        eight.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        eight.setForeground(new java.awt.Color(255, 255, 255));
        eight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eight.setText("8");
        eight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eightMouseClicked(evt);
            }
        });

        nine.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        nine.setForeground(new java.awt.Color(255, 255, 255));
        nine.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nine.setText("9");
        nine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nineMouseClicked(evt);
            }
        });

        four.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        four.setForeground(new java.awt.Color(255, 255, 255));
        four.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        four.setText("4");
        four.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fourMouseClicked(evt);
            }
        });

        five.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        five.setForeground(new java.awt.Color(255, 255, 255));
        five.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        five.setText("5");
        five.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fiveMouseClicked(evt);
            }
        });

        six.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        six.setForeground(new java.awt.Color(255, 255, 255));
        six.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        six.setText("6");
        six.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sixMouseClicked(evt);
            }
        });

        one.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        one.setForeground(new java.awt.Color(255, 255, 255));
        one.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        one.setText("1");
        one.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                oneMouseClicked(evt);
            }
        });

        two.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        two.setForeground(new java.awt.Color(255, 255, 255));
        two.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        two.setText("2");
        two.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                twoMouseClicked(evt);
            }
        });

        three.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        three.setForeground(new java.awt.Color(255, 255, 255));
        three.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        three.setText("3");
        three.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                threeMouseClicked(evt);
            }
        });

        zero.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        zero.setForeground(new java.awt.Color(255, 255, 255));
        zero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        zero.setText("0");
        zero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                zeroMouseClicked(evt);
            }
        });

        point.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        point.setForeground(new java.awt.Color(255, 255, 255));
        point.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        point.setText(".");
        point.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pointMouseClicked(evt);
            }
        });

        doublezero.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        doublezero.setForeground(new java.awt.Color(255, 255, 255));
        doublezero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        doublezero.setText("00");
        doublezero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doublezeroMouseClicked(evt);
            }
        });

        binary.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        binary.setForeground(new java.awt.Color(255, 255, 255));
        binary.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        binary.setText("B");
        binary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                binaryMouseClicked(evt);
            }
        });

        hexa.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        hexa.setForeground(new java.awt.Color(255, 255, 255));
        hexa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hexa.setText("H");
        hexa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hexaMouseClicked(evt);
            }
        });

        octal.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        octal.setForeground(new java.awt.Color(255, 255, 255));
        octal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        octal.setText("O");
        octal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                octalMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(sin, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(tan, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(seven, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(eight, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(nine, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(four, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(five, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(six, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(one, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(two, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(three, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(zero, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(doublezero, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(point, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(binary, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(octal, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(hexa, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sin, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cos, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tan, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seven, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eight, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nine, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(four, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(five, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(six, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(one, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(two, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(three, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zero, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doublezero, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(point, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(binary, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(octal, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hexa, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 19, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 195, 0));

        equals.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        equals.setForeground(new java.awt.Color(255, 255, 255));
        equals.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        equals.setText("=");
        equals.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                equalsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(equals, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(equals, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(0, 176, 255));

        clear.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        clear.setForeground(new java.awt.Color(255, 255, 255));
        clear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clear.setText("C");
        clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearMouseClicked(evt);
            }
        });

        divison.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        divison.setForeground(new java.awt.Color(255, 255, 255));
        divison.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        divison.setText("/");
        divison.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                divisonMouseClicked(evt);
            }
        });

        mult.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        mult.setForeground(new java.awt.Color(255, 255, 255));
        mult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mult.setText("X");
        mult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                multMouseClicked(evt);
            }
        });

        subs.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        subs.setForeground(new java.awt.Color(255, 255, 255));
        subs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subs.setText("-");
        subs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subsMouseClicked(evt);
            }
        });

        add.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add.setText("+");
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(divison, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(mult, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(subs, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(add, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(divison, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mult, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subs, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sinMouseClicked
        // TODO add your handling code here:
        try{
            String value=input.getText();
            double number=Double.parseDouble(value);
            double result=Math.sin((number*Math.PI)/180);
            input.setText(String.valueOf(result));
        }catch(NumberFormatException e){}
    }//GEN-LAST:event_sinMouseClicked

    private void cosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cosMouseClicked
        // TODO add your handling code here:
           try{
            String value=input.getText();
            double number=Double.parseDouble(value);
            double result=Math.cos((number*Math.PI)/180);
            input.setText(String.valueOf(result));
        }catch(NumberFormatException e){}
    }//GEN-LAST:event_cosMouseClicked

    private void tanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tanMouseClicked
        // TODO add your handling code here:
           try{
            String value=input.getText();
            double number=Double.parseDouble(value);
            double result=Math.tan((number*Math.PI)/180);
            input.setText(String.valueOf(result));
        }catch(NumberFormatException e){}
    }//GEN-LAST:event_tanMouseClicked

    private void sevenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sevenMouseClicked
        // TODO add your handling code here:
        String oldValue = input.getText();
        String setInput = "7";
        input.setText(oldValue + setInput);
    }//GEN-LAST:event_sevenMouseClicked

    private void eightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eightMouseClicked
        // TODO add your handling code here:
        String oldValue = input.getText();
        String setInput = "8";
        input.setText(oldValue + setInput);
    }//GEN-LAST:event_eightMouseClicked

    private void nineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nineMouseClicked
        // TODO add your handling code here:
        String oldValue = input.getText();
        String setInput = "9";
        input.setText(oldValue + setInput);
    }//GEN-LAST:event_nineMouseClicked

    private void fourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fourMouseClicked
        // TODO add your handling code here:
         String oldValue = input.getText();
        String setInput = "4";
        input.setText(oldValue + setInput);
    }//GEN-LAST:event_fourMouseClicked

    private void fiveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fiveMouseClicked
        // TODO add your handling code here:
         String oldValue = input.getText();
        String setInput = "5";
        input.setText(oldValue + setInput);
    }//GEN-LAST:event_fiveMouseClicked

    private void sixMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sixMouseClicked
        // TODO add your handling code here:
         String oldValue = input.getText();
        String setInput = "6";
        input.setText(oldValue + setInput);
    }//GEN-LAST:event_sixMouseClicked

    private void oneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oneMouseClicked
        // TODO add your handling code here:
         String oldValue = input.getText();
        String setInput = "1";
        input.setText(oldValue + setInput);
    }//GEN-LAST:event_oneMouseClicked

    private void twoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_twoMouseClicked
        // TODO add your handling code here:
         String oldValue = input.getText();
        String setInput = "2";
        input.setText(oldValue + setInput);
    }//GEN-LAST:event_twoMouseClicked

    private void threeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_threeMouseClicked
        // TODO add your handling code here:
         String oldValue = input.getText();
        String setInput = "3";
        input.setText(oldValue + setInput);
    }//GEN-LAST:event_threeMouseClicked

    private void zeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zeroMouseClicked
        // TODO add your handling code here:
         String oldValue = input.getText();
        String setInput = "0";
        input.setText(oldValue + setInput);
    }//GEN-LAST:event_zeroMouseClicked

    private void doublezeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doublezeroMouseClicked
        // TODO add your handling code here:
         String oldValue = input.getText();
        String setInput = "00";
        input.setText(oldValue + setInput);
    }//GEN-LAST:event_doublezeroMouseClicked

    private void pointMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pointMouseClicked
        // TODO add your handling code here:
         String oldValue = input.getText();
        String setInput = ".";
        input.setText(oldValue + setInput);
    }//GEN-LAST:event_pointMouseClicked

    private void binaryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_binaryMouseClicked
        // TODO add your handling code here:
        try{
            String binary = "";
            String value=input.getText();
            int decimal=Integer.parseInt(value);
            while(decimal > 0)
            {
                int rem = decimal % 2;
                binary = String.valueOf(rem) + binary;
                decimal = decimal / 2;
            }
            input.setText(binary);
        }catch(NumberFormatException e){}
        

    }//GEN-LAST:event_binaryMouseClicked

    private void octalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_octalMouseClicked
        // TODO add your handling code here:
        try{
            
            String octal = ""; 
            char octalchars[] = {'0','1','2','3','4','5','6','7'};   
            String value=input.getText();
            int decimal=Integer.parseInt(value);
             while(decimal > 0)  
            {  
               int rem = decimal % 8;   
               octal = octalchars[rem] + octal;   
               decimal = decimal / 8;  
            }  

            input.setText(octal);
        }catch(NumberFormatException e){}
    }//GEN-LAST:event_octalMouseClicked

    private void hexaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hexaMouseClicked
        // TODO add your handling code here:
        try{
            String hex = "";   
            char hexchars[]={'0','1','2','3','4','5','6','7','8','9','A','B','C','D','E','F'};  
            String value=input.getText();
            int decimal=Integer.parseInt(value);
             while(decimal > 0)  
            {  
              int rem = decimal % 16;   
              hex = hexchars[rem] + hex;   
              decimal = decimal / 16;  
            }
            input.setText(hex);
        }catch(NumberFormatException e){}
        
    }//GEN-LAST:event_hexaMouseClicked

    private void clearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseClicked
        // TODO add your handling code here:
        input.setText("");
        prom.setText("");
        fnumber=0;
        snumber=0;
    }//GEN-LAST:event_clearMouseClicked

    private void divisonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divisonMouseClicked
        // TODO add your handling code here:
        try{
            String value = input.getText();
            double valuenumber = Double.parseDouble(value);
            fnumber = valuenumber;
            input.setText("");
            prom.setText(value+"/");
            operation = "/";
        }catch(NumberFormatException e){}
    }//GEN-LAST:event_divisonMouseClicked

    private void multMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multMouseClicked
        // TODO add your handling code here:
        try{
            String value = input.getText();
            double valuenumber = Double.parseDouble(value);
            fnumber = valuenumber;
            input.setText("");
            prom.setText(value + "x");
            operation = "x";
        }catch(NumberFormatException e){}
    }//GEN-LAST:event_multMouseClicked

    private void subsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subsMouseClicked
        // TODO add your handling code here:
        try{
            String value = input.getText();
            double valuenumber = Double.parseDouble(value);
            fnumber = valuenumber;
            input.setText("");
            prom.setText(value + "-");
            operation = "-";
        }catch(NumberFormatException e){}
    }//GEN-LAST:event_subsMouseClicked

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
        // TODO add your handling code here:
        try{
            String value = input.getText();
            double valuenumber = Double.parseDouble(value);
            fnumber = valuenumber;
            input.setText("");
            prom.setText(value + "+");
            operation = "+";
        }catch(Exception e){}
        
    }//GEN-LAST:event_addMouseClicked

    private void equalsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equalsMouseClicked
        // TODO add your handling code here:
        try{
            switch(operation){
                case "+":
                    String valueA=input.getText();
                    snumber=Double.parseDouble(valueA);
                    double resultA=fnumber + snumber;
                    input.setText(String.valueOf(resultA));
                    prom.setText(prom.getText()+valueA);
                    break;
                case "-":
                    String valueS=input.getText();
                    snumber=Double.parseDouble(valueS);
                    double resultS=fnumber - snumber;
                    input.setText(String.valueOf(resultS));
                    prom.setText(prom.getText()+valueS);
                    break;
                case "x":
                    String valueM=input.getText();
                    snumber=Double.parseDouble(valueM);
                    double resultM=fnumber * snumber;
                    input.setText(String.valueOf(resultM));
                    prom.setText(prom.getText()+valueM);
                    break;
                case "/":
                    String valueD=input.getText();
                    snumber=Double.parseDouble(valueD);
                    double resultD=fnumber / snumber;
                    input.setText(String.valueOf(resultD));
                    prom.setText(prom.getText()+valueD);
                    break;
            }
        }catch(NumberFormatException e){}

    }//GEN-LAST:event_equalsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel add;
    private javax.swing.JLabel binary;
    private javax.swing.JLabel clear;
    private javax.swing.JLabel cos;
    private javax.swing.JLabel divison;
    private javax.swing.JLabel doublezero;
    private javax.swing.JLabel eight;
    private javax.swing.JLabel equals;
    private javax.swing.JLabel five;
    private javax.swing.JLabel four;
    private javax.swing.JLabel hexa;
    private javax.swing.JLabel input;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel mult;
    private javax.swing.JLabel nine;
    private javax.swing.JLabel octal;
    private javax.swing.JLabel one;
    private javax.swing.JLabel point;
    private javax.swing.JLabel prom;
    private javax.swing.JLabel seven;
    private javax.swing.JLabel sin;
    private javax.swing.JLabel six;
    private javax.swing.JLabel subs;
    private javax.swing.JLabel tan;
    private javax.swing.JLabel three;
    private javax.swing.JLabel two;
    private javax.swing.JLabel zero;
    // End of variables declaration//GEN-END:variables
}
